# Generated by Django 6.0.5 on 2026-05-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CREATED', 'C'), ('CONFIRMED', 'CF'), ('DELIVERED', 'D'), ('CANCELED', 'CC')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('serial_number', models.CharField(max_length=500, null=True, unique=True)),
                ('manufacturer', models.CharField(choices=[('Apple Inc.', 'apple')], max_length=500, null=True)),
                ('production_year', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('quantity_available', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(null=True)),
                ('sale_start', models.DateTimeField()),
                ('sale_end', models.DateTimeField()),
                ('category', models.CharField(choices=[('E', 'ELECTRONICS')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
